# Essential Python Programming Topics for Machine Learning and AI

## 1. Basic Python Programming
- Variables and Data Types
- Control Structures (if-else, loops)
- Functions and Lambda Functions
- List Comprehensions
- Exception Handling

## 2. Data Structures
- Lists, Tuples, and Sets
- Dictionaries
- Arrays (using NumPy)

## 3. Libraries and Frameworks
- **NumPy**: Array operations, linear algebra
- **Pandas**: Data manipulation, DataFrames, and Series
- **Matplotlib & Seaborn**: Data visualization
- **Scikit-learn**: Core machine learning algorithms
- **TensorFlow** / **PyTorch**: Deep learning frameworks
- **Keras**: High-level neural network API
- **SciPy**: Scientific and technical computing
- **NLTK** / **spaCy**: Natural Language Processing

## 4. Data Handling and Manipulation
- Reading/Writing Data Files (CSV, Excel, JSON)
- Data Cleaning and Preprocessing
- Handling Missing Data
- Feature Engineering
- Data Normalization and Scaling

## 5. Mathematical Foundations
- **Linear Algebra**: Vectors, matrices, matrix operations
- **Probability and Statistics**: Probability distributions, statistical tests, hypothesis testing
- **Calculus**: Differentiation, gradients (for optimization algorithms)

## 6. Machine Learning Concepts
- Supervised vs. Unsupervised Learning
- Regression and Classification Algorithms
- Decision Trees, Random Forests
- k-Nearest Neighbors (k-NN)
- Support Vector Machines (SVM)
- Clustering (k-Means, Hierarchical)
- Dimensionality Reduction (PCA, t-SNE)
- Model Evaluation and Validation Techniques (Cross-validation, AUC-ROC)

## 7. Deep Learning
- Neural Networks (ANNs, CNNs, RNNs)
- Activation Functions
- Loss Functions
- Backpropagation and Gradient Descent
- Convolutional Neural Networks (CNNs) for image processing
- Recurrent Neural Networks (RNNs) and LSTMs for sequential data

## 8. Natural Language Processing (NLP)
- Text Preprocessing (Tokenization, Lemmatization, Stemming)
- Word Embeddings (Word2Vec, GloVe)
- Sentiment Analysis
- Text Classification

## 9. Model Deployment
- Saving and Loading Models (Pickle, Joblib)
- Flask/Django for creating APIs
- Model Serving (TensorFlow Serving, TorchServe)
- Deployment on Cloud Platforms (AWS, GCP, Azure)

## 10. Advanced Topics
- Transfer Learning
- Reinforcement Learning
- Generative Adversarial Networks (GANs)
- Time Series Forecasting
- Hyperparameter Tuning (Grid Search, Random Search)
- AutoML (Automated Machine Learning)

## 11. Version Control and Collaboration
- Git and GitHub for version control
- Jupyter Notebooks for interactive development


## 1. Basic Python Programming
- Variables and Data Types
- Control Structures (if-else, loops)
- Functions and Lambda Functions
- List Comprehensions
- Exception Handling

In [1]:
p = (4,5)
print(p)


(4, 5)


## 2. Data Structures
- Lists, Tuples, and Sets
- Dictionaries
- Arrays (using NumPy)

## 3. Libraries and Frameworks
- **NumPy**: Array operations, linear algebra
- **Pandas**: Data manipulation, DataFrames, and Series
- **Matplotlib & Seaborn**: Data visualization
- **Scikit-learn**: Core machine learning algorithms
- **TensorFlow** / **PyTorch**: Deep learning frameworks
- **Keras**: High-level neural network API
- **SciPy**: Scientific and technical computing
- **NLTK** / **spaCy**: Natural Language Processing

# Numpy

## Creating and Manipulating Arrays
Program: Create a 1D, 2D, and 3D array and print their shapes.

In [6]:
import numpy as np

arr1d = np.array([1, 12, 3])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("1D Array:", arr1d)
print("2D Array:\n", arr2d)
print("3D Array:\n", arr3d)
print("Shapes:", arr1d.shape, arr2d.shape, arr3d.shape)
print(arr1d.all())


1D Array: [ 1 12  3]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shapes: (3,) (2, 3) (2, 2, 3)
True


## Array Indexing and Slicing
- Program: Demonstrate slicing and indexing on a 2D array

In [9]:
print(arr3d[:,1])

[[ 4  5  6]
 [10 11 12]]


## Array Operations


In [16]:
arr1 = np.array([2,2])
print(arr1)

[2 2]


## Broadcasting
- Program: Demonstrate NumPy broadcasting by adding a 1D array to a 2D array

In [20]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

result = arr2d + arr1d

print("Broadcasted Result:\n", result)


Broadcasted Result:
 [[11 22 33]
 [14 25 36]]


## Array Aggregations
- sum, mean, max, min

In [27]:
a1 = np.array([1,2,3,4,5])
print(a1.max())
print(np.max(a1))
print(a1+10)

5
5
[11 12 13 14 15]


## Reshaping

a1 = np.array([[1,2,3],[4,5,6]])
a2 = a1.reshape([6])
print(a2)

## Matrix multiplication

In [39]:
arr2d_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2d_2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2d_3 = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(arr2d_1 + arr2d_2)
print(arr2d_1 * arr2d_2)
print(np.matmul(arr2d_1, arr2d_3))
arr2d_1.sort()

[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[30 36 42]
 [66 81 96]]


In [1]:
import pandas as pd
# Create a DataFrame from a list of lists
df2 = pd.DataFrame([
    ['Dave', 40, 'San Francisco'],
    ['Eve', 22, 'Houston']
], columns=['Name', 'Age', 'City'])
print(df2)


   Name  Age           City
0  Dave   40  San Francisco
1   Eve   22        Houston


In [ ]:
!brew install pandas


==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).


In [15]:
import pandas as pd
import numpy as np
mydata = {"Names":"a,b,c,d,e,f,g,h".split(","), "ranks":[i  for i in range(8)]}
mydata["ranks"][1] = np.nan
print(mydata)
d1 = pd.DataFrame(data=mydata)
d2 = d1.fillna(0)
print(d2)

{'Names': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], 'ranks': [0, nan, 2, 3, 4, 5, 6, 7]}
  Names  ranks
0     a    0.0
1     b    0.0
2     c    2.0
3     d    3.0
4     e    4.0
5     f    5.0
6     g    6.0
7     h    7.0


In [14]:
import pandas as pd
import numpy as np

# Create the dictionary with data
mydata = {
    "Names": "a,b,c,d,e,f,g,h".split(","),
    "ranks": [i for i in range(8)]
}

# Introduce NaN into the data
mydata["ranks"][1] = np.nan

# Create a DataFrame
d1 = pd.DataFrame(data=mydata)

# Fill NaN values with 0 (without modifying the original DataFrame)
d1_filled = d1.fillna(0)

# Print the filled DataFrame
print(d1_filled)


  Names  ranks
0     a    0.0
1     b    0.0
2     c    2.0
3     d    3.0
4     e    4.0
5     f    5.0
6     g    6.0
7     h    7.0


In [60]:

import numpy as np
import pandas as pd


SalesData = {
    'TransactionID': range(1,11),
    'ProductID': np.random.randint(10),
    'Quantity': [1,2,3,1,1,2,1,4,5,10],
    'Price':np.random.choice([1,2,3,np.nan, 9.0],10),
    'TransactionsData': pd.date_range(start="2024-08-1", periods=10, freq='D')
}

d1 = pd.DataFrame(data=SalesData)
print(d1)
# Replace NAN with 0
#d1['Price'] = d1['Price'].apply(lambda x: 0 if x==np.nan else x)
# d2 = d1.fillna(0)
d1["Price"] = [0 if item==np.nan else item for item in d1["Price"]] 
print(d2)
# Add Calculating sales
d1['Sales'] = d1['Quantity']*d1['Price']
print(d1)


   TransactionID  ProductID  Quantity  Price TransactionsData
0              1          9         1    2.0       2024-08-01
1              2          9         2    9.0       2024-08-02
2              3          9         3    3.0       2024-08-03
3              4          9         1    NaN       2024-08-04
4              5          9         1    2.0       2024-08-05
5              6          9         2    NaN       2024-08-06
6              7          9         1    NaN       2024-08-07
7              8          9         4    NaN       2024-08-08
8              9          9         5    3.0       2024-08-09
9             10          9        10    9.0       2024-08-10
   TransactionID  ProductID  Quantity  Price TransactionsData
0              1          5         1    0.0       2024-08-01
1              2          5         2    0.0       2024-08-02
2              3          5         3    3.0       2024-08-03
3              4          5         1    2.0       2024-08-04
4       

In [61]:
#Filter list where

TypeError: 'module' object is not callable